sudo: false
language: generic

matrix:
  include:
    - name: Python
      language: python
      python:
        - "3.6"
      install:
        - pip install -r open_widget_framework/test_requirements.txt
      script: ./travis/py_tests.sh
    - name: JavaScript
      language: javascript
      script: bash ./travis/js_tests.sh
