# Generated by Django 2.1.1 on 2018-09-27 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WidgetInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_type", models.CharField(max_length=200)),
                ("configuration", django.contrib.postgres.fields.jsonb.JSONField()),
                ("position", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WidgetList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.AddField(
            model_name="widgetinstance",
            name="widget_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="open_widget_framework.WidgetList",
            ),
        ),
    ]
