# Generated by Django 2.1.2 on 2018-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_widget_framework', '0002_auto_20181001_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetinstance',
            name='react_renderer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='widget_class',
            field=models.CharField(choices=[('Text', 'Text'), ('URL', 'URL'), ('Many User', 'Many User')], max_length=200),
        ),
    ]
